### ISSUE TITLE
I'm just getting errors trying to run this..

### ISSUE THREAD

**Issue by nichroot** [cel7t/plyppy#1]
So, I tried two ways, through pipx and then by creating a venv too, both had errors. These are the logs when i created the venv (it might be something dumb from my side too)

./pip install .

Processing /home/em-en/plyppy/bin
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "/home/em-en/plyppy/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/em-en/plyppy/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/em-en/plyppy/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 72, in apply_configuration
          return _apply(dist, config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 52, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 78, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 159, in _long_description
          ctype = _guess_content_type(file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8y7ru7pk/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 149, in _guess_content_type
          raise ValueError(f"Undefined content type for {file}, {msg}")
      ValueError: Undefined content type for README.org, only the following file extensions are recognized: .md (text/markdown), .rst (text/x-rst), .txt (text/plain).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip

**Comment by matchcase** [comment]
Hey MKnoder,
Thank you for pointing out the error.
I made a new commit that should fix it.
The error is being caused because pip isn't recognising the extension type
of my README file, so I changed it to one that works and it should build
successfully now.
